### ISSUE TITLE
UIOWA-PCORnet Tumor Table Linkage

### ISSUE THREAD

**Issue by vyshu1094** [gpcnetwork/gpc-tumor-table#11]
- [x] Populate PCORnet TUMOR table with data from hospital tumor registry files (NAACCR format)- **Due date: 10/01/2022**
- [x] Run data quality scripts and share output - **Due date: 11/08/2022** Here is the link to the REDCap for submitting that: https://showmeportal.missouri.edu/redcap/surveys/?s=CAPM9RXAKFLWRPCF
 
- [x] Data remediation of identified issues - **Due date: 12/01/2022**

**Comment by bgryzlak** [comment]
@mcdowellb755  or @spinkac are there other remediation issues that UIowa still needs to complete?

**Comment by mcdowellb755** [comment]
No issues!

**Comment by bgryzlak** [comment]
awesome - thanks.

**Comment by bgryzlak** [comment]
@vyshu1094  i think you can close this ticket
