### ISSUE TITLE
UNMC-PCORnet Tumor Table Linkage

### ISSUE THREAD

**Issue by vyshu1094** [gpcnetwork/gpc-tumor-table#12]
- [x] Populate PCORnet TUMOR table with data from hospital tumor registry files (NAACCR format)- **Due date: 10/01/2022**
- [x] Run data quality scripts and share output - **Due date: 11/08/2022** Here is the link to the REDCap for submitting that: https://showmeportal.missouri.edu/redcap/surveys/?s=CAPM9RXAKFLWRPCF
 
- [x] Data remediation of identified issues - **Due date: 12/01/2022**

**Comment by Fwolfeunmc** [comment]
Hi, This is still showing up as a Major To Do in github. We have completed all requested work. Is there something more desired? Thank you!

**Comment by Fwolfeunmc** [comment]
Update: We have received specific feedback from Brad McDowell (thank you!). Jim Svoboda will reach out to Brad for clarification on some items so we can work through the issues outlined.

**Comment by Fwolfeunmc** [comment]
Jim Svoboda's note regarding noted issues.  Will wait to hear from Brad McDowell.

**Minor:** MRN is in the tumor table: recommend that the PATID/MRN crosswalk be stored in a separate mapping file.
>>  MRN and MEDICAL_RECORD_NUMBER_N2300 are in table TUMOR (local only, identified dataset) but not in table TUMOR_SAS (the columns are present but set to null for all records)
>>  when working with PCORNET/GPC, always use TUMOR_SAS
>>  **no issue here**

**Minor:** Most of the variables with high missingness are the stage variables, and this is common across sites. We may need to revisit which stage variables are included in this QC query.
>> if you have specific variables to review let me know
>> **the values reflect what is present in the NAACCR files, with identified information removed**

**Major:** There are a large number of cases without encounters (18%). A similarly large number of tumor registry cases have diagnoses prior to 2010. Is it possible that older cases in the registry do not map to other cases in the CDM? How would this look if tumor registry cases diagnosed prior to 2010 were dropped?
>> most of the items are very old (2012 or earlier, so currently excluded from our CDM with 10 year range)
>> this query will show the items:
select distinct a.patid, a.DATE_OF_DIAGNOSIS_N390, b.*
from tumor a
left join cdmv6.dbo.demographic b on a.patid = b.patid where b.patid is null
order by DATE_OF_DIAGNOSIS_N390 desc 
>> I modified the stored proc that creates TUMOR_SAS to limit date of diagnosis to past 10 years (since corresponding data is not in CDM).
>> **resolved**

**Major:** There are many duplicates of tumor records (i.e., unique PATID-SEQ_NUM combinations with multiple records); about 28% of tumors have two or more records. I suspect many of these multiple records per tumor represent updated records as additional information is available to the tumor registry.
>> we keep data for 2 institutions in our table:  0010000066 (NMC) and 0010001153 (BMC)
>> a given patient and tumor ID can be in both institutions’ data set, and so they are stored as two rows
>> the key for out table is:  MEDICAL_RECORD_NUMBER_N2300, TUMOR_RECORD_NUMBER_N60, and REGISTRY_ID_N40
>> there are no duplicates when using this key
>> NOTE:  there were other duplicate due to bad data in MEDICAL_RECORD_NUMBER_N2300:
-	In the NAACCR file, sometimes the value would be “99999999” and sometimes the value would be “     99999999”  (the value prepended with spaces)
-	This created two records.   These duplicates how now been removed.
>> **resolved**
